
name: Compile Vue application

on:
  push:
    branches:
      - '*'
      - '!deployment'
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        shell: bash
        run: |
          npm install

      - name: Build app
        shell: bash
        run: |
          npm run build

      - name: Upload app artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Test project
        shell: bash
        run: |
          npm run test:unit

      - name: Lint project
        shell: bash
        run: |
          npm run lint

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: deployment

      - run: |
          git reset --hard e402c8009bb77f1942731a9f7c79048eda8dec7a
          rm -rf dist

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Autogenerated deployment commit for $(date +%Y-%m-%d_%H-%M)" || true
          git push --force
